remote_theme: qwtel/hydejack

title: Austin Huang

# Default:
tagline: A young JavaScript developer who writes chatbots and stories in Montreal.
accent_color: '#bada55'
accent_image: ''
background: '#bada55'

# Remembrance Day:
# tagline: On November 11, We Remember.
# accent_color: '#d8002b'
# accent_image: /assets/poppy.jpg
# background: '#d8002b'
  
disqus: '0131'

url: https://austinhuang.me

author:
  name:  Austin Huang
  email: im@austinhuang.me
  social:
    email: mailto:im@austinhuang.me
    github: austinhuang0131
    flickr: austin0131
    instagram: austinhuang.me
    paypal: discordtel
    telegram: austinhuang
    tumblr: austinhuang0131
    twitter: montreal0131
    reddit: austinhuang
    steam: austinhuang0131

include:
  - assets
exclude:
  - Makefile
